### ISSUE TITLE
Create Wallet address offline from seed

### ISSUE THREAD

**Issue by kokill** [iotaledger/iota.lib.js#129]
I tried creating wallet address from seed without running any node on my localhost.
```
var IOTA = require('iota.lib.js');
var iota = new IOTA({});
iota.api.getNewAddress('[81 character seed]', {}, function(e, s) {
 if (e) {
  console.log('Error:', e);
 } else {
   console.log('Address: ', s);
  }
})
```
but it throws error `Invalid Response: Error: connect ECONNREFUSED 127.0.0.1:14265`

but this [Project](https://github.com/domschiener/iota-address-generator) works offline and creates address without starting any new node.

Any suggestions how to create wallet offline ?

**Comment by Xflofoxx** [comment]
I think that your problem is in the way you initialize IOTA library.
Try:
```javascript
var iota = new IOTA({
        // Host and provider are only needed if the user intends to generate the address deterministically
        'host': 'http://localhost',
        'port': 14265
    });
```

**Comment by Xflofoxx** [comment]
Try 
```
var iota = new IOTA(); //without the {}
```

**Comment by l3wi** [comment]
This function checks the network for latest index. You have to explicitly put in the required indexes to create the address offline

**Comment by vbakke** [comment]
Not quite, l3wi. One has to specify the number of addresses to generate. (Maybe a bit counter intuitive, but that is how the lib works at the moment.)

So, to make it work offline, you need to write: `iota.api.getNewAddress('[81 character seed]', {total: 1}, function(e, s) {` 
 
Of course, you then need to ensure that the address has not previously been used, since the lib does not check it for you.


Could you confirm @kokill, that this works for you as well, and that the issue may be closed with a workaround?

Cheers

**Comment by chrisdukakis** [comment]
As @vbakke written `total` option should work. 
This is responsibility overload for `getNewAddress()` which should do only one thing: Generate a new (unused) address. Therefore some options will be deprecated in v1.0.0 and removed in a timely manner.
A new method is being added: `generateAddress(seed, index, security, checksum)` which works offline. (https://github.com/iotaledger/iota.lib.js/blob/next/lib/crypto/address.ts#L6)
