### ISSUE TITLE
Not enough balance

### ISSUE THREAD

**Issue by fsanano** [iotaledger/iota.lib.js#227]
I try send transfer, but every time catch `Not enough balance`
```
const seed = 'some seed';
// const seed = utils.toTrytes('some seed');

const address = utils.noChecksum('address');
// const address = 'address';


const transfers = [{
  address: address,
  value: Number(this.form.coinAmount),
  message: '',
  tag: '',
}];

iota.sendTransfer(seedTrytes, this.depth, this.minWeightMagnitude, transfers, {}, (err) => {
  if (err) {
    this.canSendTransaction = true;
    this.$store.dispatch('addNotification', {
      type: 'error',
      text: 'Not enough balance',
    });
    console.log(err);// eslint-disable-line
  } else {
    this.clearForm();
    this.iotaFetchWalletsData();
  }
});
```

Also I try send transaction different variation of address and seed

`seed and address`
`seed and addressNoChecksum`
`seedTrytes and address`
`seedTrytes and addressNoChecksum`

One response 'Not enough balance'
But I send from this [wallet](https://thetangle.org/address/WOAULDGVYXLVDBUQGVXQPRXOBQAVHOOPBWI9HR9FAOHFIQBWIMANZTHUGZITYGPDTOEHJMWJNSHYJ9EPXTJODCNJYX) with 20ki

**Comment by chrisdukakis** [comment]
Hi @fsanano, assuming you wallet has balance, please make sure that all addresses up to the one(s) with balance are attached to tangle so that `getInputs` (called by `sendTransfer`) can pick them. 

For best performance you can try to pass the inputs manually with `options.inputs`.

Also do not use non-trytes for seeds and **do NOT** convert from non-trytes. Simply generate a seed consisting of `A-Z9's`

**Comment by chrisdukakis** [comment]
Hi @fsanano , coins are sent to remainder address as returned by `getNewAddress(seed)`.
Addresses reuse is insecure, therefore library generates new address and transfers remainder value there.
I tag this with `support` label and closing, as it's non issue, but feel free to continue the discussion, preferably on [IOTA Discord](https://discord.gg/DTbJufa).
