### ISSUE TITLE
Support remote authentication

### ISSUE THREAD

**Issue by bmavity** [iotaledger/iota.lib.js#34]
My ultimate goal is to add authentication to the iota wallet. However, this library currently only allows users to set a token as seen at

https://github.com/iotaledger/iota.lib.js/blob/master/lib/utils/makeRequest.js#L37

Unfortunately, this does not properly authorize a request to a headless node running `--remote`. I was considering adding `settings.user` and `settings.pass` to the library and doing basic auth if those values were present, but I was not sure if `settings.token` was supposed to be used for this purpose.

If someone could let me know which option to use, I will get you a pull request later today.

**Comment by alfredch** [comment]
Did you actually test it by calling an IRI node that has authentication configured? Because I tried some similar code and it was a failure.
Finally, I set the parameters 'user' and 'password' like this:
request.open('POST', this.provider, true, 'user', 'password');
in https://github.com/iotaledger/iota.lib.js/blob/master/lib/utils/makeRequest.js#L32
That did work.  What is the advantage of your way of implementation?

**Comment by bmavity** [comment]
Hi, I am connecting successfully to an IRI node that has authentication configured.

The advantage of this implementation is that it still allows the token auth that was already built. But certainly I am open to change the implementation if it is not following this project's coding standards.

**Comment by tuddman** [comment]
I got `REMOTE_AUTH` to work by to changing https://github.com/iotaledger/iota.lib.js/blob/master/lib/utils/makeRequest.js#L37 to 

```
       request.setRequestHeader('Authorization', 'Basic ' + this.token);
```

with the token being the `base64` encoding of  `user:sufficientlylongsecurelygeneratedpassword`
