### ISSUE TITLE
promises support

### ISSUE THREAD

**Issue by capaj** [iotaledger/iota.lib.js#59]
I prefer to write my JS with async/await and the readme only shows callback style. So I have to ask-is there no planned support for promises?
I already created a similar issue here:
 https://github.com/iotaledger/iota.crypto.js/issues/4
but it would be great to have it in both.

**Comment by chrisdukakis** [comment]
Support for promises is planned and will be added soon.
Promises are not needed for `iota.crypto.js`, all methods are synchronous.

**Comment by capaj** [comment]
@chrisdukakis makes sense. Thanks for a quick response.

**Comment by jimthedev** [comment]
In the mean time you can use https://github.com/jimthedev/iotap which tries to promisify the existing api. It is quite small (a single fn) and PRs are of course welcome.

**Comment by brunoamancio** [comment]
https://github.com/iotaledger/iota.lib.js/pull/89

**Comment by jkoudys** [comment]
If we're introducing promises, how about taking it a step further with full `async`/`await` support?

**Comment by capaj** [comment]
@jkoudys if it's returning a promise you can await it. There's no extra step a library needs to make to allow async/await.

**Comment by jkoudys** [comment]
@capaj I was referring to using async/await in the project code itself, instead of building promises the old fashioned way. Since there's no transpiling happening yet when building for `/dist` that's not feasible until we introduce babel.

**Comment by anyong** [comment]
@capaj @jkoudys first of all, thanks for keeping this conversation going!

Promise support is available in the [`next` branch](https://github.com/iotaledger/iota.lib.js/tree/next) right now, but we decided to go with Bluebird since we like the API it provides, and using async/await precludes changing the Promise implementation, which means we don't get things like `.asCallback`. I hope this is satisfactory for now...

**Comment by capaj** [comment]
@anyong I am not sure why you'd say that bluebird is incompatible with async/await. async/await doesn't care whether the promise is native or bluebird. If it has methods `then` and `catch` it works every time.

**Comment by anyong** [comment]
@capaj if you try to import a custom promise (and name it `Promise`) in a TypeScript file with async/await, you get the following error:

```
[ts] Duplicate identifier 'Promise'. Compiler reserves name 'Promise' in top level scope of a module containing async functions.
```

There are various issues around the TypeScript repo with possible fixes:

https://github.com/Microsoft/TypeScript/issues/8331
https://github.com/Microsoft/TypeScript/issues/12323
https://github.com/Microsoft/TypeScript/issues/12374

The considerations for sticking with Promise were:

- Single promise implementation throughout the code
- Easily support callbacks for legacy compatibility
- Not implementing workaround / special case to support custom promise with async/await

You will be able to `await` all async methods from iota.lib.js in your own code now, and we could definitely explore using async/await in the new codebase since it is supported by TS directly with no additional compilation steps.

**Comment by capaj** [comment]
thanks for clarification

**Comment by anyong** [comment]
@capaj would you be OK with closing this issue now or is there anything else we should discuss here?

**Comment by capaj** [comment]
well best practice is to close this when "next" branch is published to npm as the latest version, but I can live with this being closed now 💪

**Comment by chrisdukakis** [comment]
Promises on next or master are here to stay, I promise!
